// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xV34vbRhD+V5ZpoQnobPlCX/QWaBsOUnqklDyEI6y1I3mC9kdmR7mYw/972ZVkK7bM",
	"cW95uvXO6Pu+mdlv7glqb4N36CRC9QSx3qHV+fgns+d0COwDshDm69obTH8NxpopCHkH1ZCscqyAxrPV",
	"AhWQkze3UIDsAw4/sUWGQwEWY9TtVaApfPw0CpNr4XAogPFrT4wGqk8wEk7pD4cC/ou4oBqtpi4dzvAK",
	"ILN47bTFxUDYeYcLbcFuGd9qcguBw7E0v/2CtWRoqqXnBfBOc7usxqKh3i6GZNfbrVsue4mdsaUorNMg",
	"PhstmfA4ynRxI2SfnwkZGNtXjG1fwn64UJBwyDU+yyXpUuzvvfronUFu+k69vb+DAr4hx+GpbFblqkzK",
	"fUCnA0EFb1abVQkFBC273Ll18KHvxmKCj3L54t4aE9XvRVmWirUz3qo+Iit0woRRNeyt+pAD6X5Ve5uU",
	"rCDzDiXdGajg3ke5n9hSyTF4F4cB3pabS+J/+7rGGFMFBhvddzL4ywm6fNQhdFRnhvWX6N3JoOn0K2MD",
	"FfyyPjl4Pdp3PXg3t/RHzt7h94C1oFE45hQQe2s173MNg35ltOitjqgeSXbzvsT8xfpxmkour8WFvn5A",
	"6dlFpVVHUZRvhu8HRJ+zdKca6gTTO1LaGRV0Sy4XfNnfdygfT6xpxqwtSpJUfXo6tfC2PC/6PVkSJTtU",
	"rrdb5KSFszo0o6hXm5tNWb6G9AShgq898j4tFv2dbPLXpiwLsOTGX9N+gC5BQzEby/muOxTnjUkbSt39",
	"ocSrKJplVrXSjSCfqxi5cjK59vOUdEF6cuRLOLfYeMYrpOhMojzmvIDzrzxatd3nHv8WVd4G6lWtI96Q",
	"i+giCX3D19eox+VxnfLhwmbliyxEgjY+56X8D+W0MDWz3i9Z6/38lf9Mpn6H8qMFBwzR7eScOdg/k+mi",
	"0lvfi3qcm24czcyIl3OfIYhX0wLO/pvWygnpuDEPD4f/AwAA//9Qr0XZjQgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
