// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email string `json:"email"`
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone *struct {
		Cell *string `json:"cell,omitempty"`
		Main *string `json:"main,omitempty"`
	} `json:"phone,omitempty"`
	Picture *struct {
		Large     *string `json:"large,omitempty"`
		Medium    *string `json:"medium,omitempty"`
		Thumbnail *string `json:"thumbnail,omitempty"`
	} `json:"picture,omitempty"`
	RegistrationDate time.Time `json:"registration_date"`
}

// GetWonderfulsParams defines parameters for GetWonderfuls.
type GetWonderfulsParams struct {
	// Limit Limit the number of returned users (1-100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter User ID to start pagination after
	StartingAfter *string `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore User ID to start pagination before
	EndingBefore *string `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// Email Filter by user's email (case-insensitive)
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}
