// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForLoadBulkUsers implements pgx.CopyFromSource.
type iteratorForLoadBulkUsers struct {
	rows                 []LoadBulkUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForLoadBulkUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForLoadBulkUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Email,
		r.rows[0].Phone,
		r.rows[0].Cell,
		r.rows[0].Picture,
		r.rows[0].Registration,
	}, nil
}

func (r iteratorForLoadBulkUsers) Err() error {
	return nil
}

func (q *Queries) LoadBulkUsers(ctx context.Context, arg []LoadBulkUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "name", "email", "phone", "cell", "picture", "registration"}, &iteratorForLoadBulkUsers{rows: arg})
}
