// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUsers = `-- name: ListUsers :many
WITH cursor_data AS (
    -- Get cursor reference data in a single query
    SELECT 
        CASE WHEN $2 != '' AND $2 IS NOT NULL THEN
            (SELECT registration FROM users WHERE id = $2)
        END as starting_after_registration,
        CASE WHEN $3 != '' AND $3 IS NOT NULL THEN
            (SELECT registration FROM users WHERE id = $3)
        END as ending_before_registration
)
SELECT
    u.id,
    u.name,
    u.email,
    u.phone,
    u.cell,
    u.picture,
    u.registration
FROM
    users u
CROSS JOIN cursor_data c
WHERE
    -- email substring
    (u.email LIKE '%' || $1 || '%' OR $1 IS NULL)
    -- starting_after - using composite comparison for efficiency
    AND ($2 = '' OR $2 IS NULL OR ( 
        (u.registration < c.starting_after_registration) OR 
        (u.registration = c.starting_after_registration AND u.id < $2)
    ))
    -- ending_before - using composite comparison for efficiency  
    AND ($3 = '' OR $3 IS NULL OR ( 
        (u.registration > c.ending_before_registration) OR 
        (u.registration = c.ending_before_registration AND u.id > $3)
    ))
ORDER BY
    u.registration DESC, u.id DESC
LIMIT $4
`

type ListUsersParams struct {
	Column1 pgtype.Text
	Column2 interface{}
	Column3 interface{}
	Limit   int32
}

type ListUsersRow struct {
	ID           string
	Name         string
	Email        string
	Phone        string
	Cell         pgtype.Text
	Picture      []byte
	Registration pgtype.Timestamp
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Cell,
			&i.Picture,
			&i.Registration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type LoadBulkUsersParams struct {
	ID           string
	Name         string
	Email        string
	Phone        string
	Cell         pgtype.Text
	Picture      []byte
	Registration pgtype.Timestamp
}
